<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DoctorSeeder extends Seeder
{
    public function run(): void
    {
        $doctors = [
            // Doctor 1 (User ID: 11)
            [
                'stop_booking' => 0,
                'user_id' => 11,
                'department' => 1, // Cardiology
                'description' => 'Heart specialist with 10 years of experience',
                'specialization' => 'Cardiologist',
                'ex_year' => 10,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 200,
                'video_fee' => 150,
                'emg_fee' => 0,
                'zoom_client_id' => 'zoom_client_123',
                'zoom_secret_id' => 'zoom_secret_456',
                'insta_link' => 'https://instagram.com/dr.john',
                'fb_linik' => 'https://facebook.com/dr.john',
                'twitter_link' => 'https://twitter.com/dr.john',
                'you_tube_link' => 'https://youtube.com/drjohn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 2 (User ID: 12)
            [
                'stop_booking' => 0,
                'user_id' => 12,
                'department' => 2, // Pediatrics
                'description' => 'Child health expert, vaccinations and growth monitoring.',
                'specialization' => 'Pediatrician',
                'ex_year' => 8,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 300,
                'video_fee' => 1200,
                'emg_fee' => 500,
                'zoom_client_id' => 'zoom_client_124',
                'zoom_secret_id' => 'zoom_secret_457',
                'insta_link' => 'https://instagram.com/dr.pediatrics',
                'fb_linik' => 'https://facebook.com/dr.pediatrics',
                'twitter_link' => 'https://twitter.com/dr_pediatrics',
                'you_tube_link' => 'https://youtube.com/dr.pediatrics',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 3 (User ID: 13)
            [
                'stop_booking' => 0,
                'user_id' => 13,
                'department' => 3, // Gynecology
                'description' => 'Women\'s health, pregnancy, childbirth, and reproductive care.',
                'specialization' => 'Gynecologist',
                'ex_year' => 12,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 400,
                'video_fee' => 1300,
                'emg_fee' => 600,
                'zoom_client_id' => 'zoom_client_125',
                'zoom_secret_id' => 'zoom_secret_458',
                'insta_link' => 'https://instagram.com/dr.gynecology',
                'fb_linik' => 'https://facebook.com/dr.gynecology',
                'twitter_link' => 'https://twitter.com/dr_gynecology',
                'you_tube_link' => 'https://youtube.com/dr.gynecology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 4 (User ID: 14)
            [
                'stop_booking' => 0,
                'user_id' => 14,
                'department' => 4, // Orthopedics
                'description' => 'Bone and joint specialist with expertise in fractures and arthritis.',
                'specialization' => 'Orthopedic Surgeon',
                'ex_year' => 15,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 500,
                'video_fee' => 1400,
                'emg_fee' => 700,
                'zoom_client_id' => 'zoom_client_126',
                'zoom_secret_id' => 'zoom_secret_459',
                'insta_link' => 'https://instagram.com/dr.orthopedics',
                'fb_linik' => 'https://facebook.com/dr.orthopedics',
                'twitter_link' => 'https://twitter.com/dr_orthopedics',
                'you_tube_link' => 'https://youtube.com/dr.orthopedics',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 5 (User ID: 15)
            [
                'stop_booking' => 0,
                'user_id' => 15,
                'department' => 5, // Dermatology
                'description' => 'Skin care and cosmetic dermatology expert.',
                'specialization' => 'Dermatologist',
                'ex_year' => 9,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 0,
                'opd_fee' => 350,
                'video_fee' => 1100,
                'emg_fee' => 0,
                'zoom_client_id' => 'zoom_client_127',
                'zoom_secret_id' => 'zoom_secret_460',
                'insta_link' => 'https://instagram.com/dr.dermatology',
                'fb_linik' => 'https://facebook.com/dr.dermatology',
                'twitter_link' => 'https://twitter.com/dr_dermatology',
                'you_tube_link' => 'https://youtube.com/dr.dermatology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 6 (User ID: 16) - Psychiatry
            [
                'stop_booking' => 0,
                'user_id' => 16,
                'department' => 6,
                'description' => 'Mental health specialist handling anxiety, depression, and schizophrenia.',
                'specialization' => 'Psychiatrist',
                'ex_year' => 14,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 450,
                'video_fee' => 1250,
                'emg_fee' => 500,
                'zoom_client_id' => 'zoom_client_128',
                'zoom_secret_id' => 'zoom_secret_461',
                'insta_link' => 'https://instagram.com/dr.psychiatry',
                'fb_linik' => 'https://facebook.com/dr.psychiatry',
                'twitter_link' => 'https://twitter.com/dr_psychiatry',
                'you_tube_link' => 'https://youtube.com/dr.psychiatry',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 7 (User ID: 17) - Neurology
            [
                'stop_booking' => 0,
                'user_id' => 17,
                'department' => 7,
                'description' => 'Specialist in brain and nervous system disorders, migraines and epilepsy.',
                'specialization' => 'Neurologist',
                'ex_year' => 11,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 400,
                'video_fee' => 1300,
                'emg_fee' => 600,
                'zoom_client_id' => 'zoom_client_129',
                'zoom_secret_id' => 'zoom_secret_462',
                'insta_link' => 'https://instagram.com/dr.neurology',
                'fb_linik' => 'https://facebook.com/dr.neurology',
                'twitter_link' => 'https://twitter.com/dr_neurology',
                'you_tube_link' => 'https://youtube.com/dr.neurology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 8 (User ID: 18) - Radiology
            [
                'stop_booking' => 0,
                'user_id' => 18,
                'department' => 8,
                'description' => 'Imaging and diagnostics expert, X-rays, MRI, CT scans.',
                'specialization' => 'Radiologist',
                'ex_year' => 13,
                'active' => 1,
                'video_appointment' => 0,
                'clinic_appointment' => 1,
                'emergency_appointment' => 0,
                'opd_fee' => 400,
                'video_fee' => 0,
                'emg_fee' => 0,
                'zoom_client_id' => 'zoom_client_130',
                'zoom_secret_id' => 'zoom_secret_463',
                'insta_link' => 'https://instagram.com/dr.radiology',
                'fb_linik' => 'https://facebook.com/dr.radiology',
                'twitter_link' => 'https://twitter.com/dr_radiology',
                'you_tube_link' => 'https://youtube.com/dr.radiology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 9 (User ID: 19) - Ophthalmology
            [
                'stop_booking' => 0,
                'user_id' => 19,
                'department' => 9,
                'description' => 'Eye care specialist for cataracts, glaucoma, and vision correction.',
                'specialization' => 'Ophthalmologist',
                'ex_year' => 10,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 0,
                'opd_fee' => 350,
                'video_fee' => 1200,
                'emg_fee' => 0,
                'zoom_client_id' => 'zoom_client_131',
                'zoom_secret_id' => 'zoom_secret_464',
                'insta_link' => 'https://instagram.com/dr.ophthalmology',
                'fb_linik' => 'https://facebook.com/dr.ophthalmology',
                'twitter_link' => 'https://twitter.com/dr_ophthalmology',
                'you_tube_link' => 'https://youtube.com/dr.ophthalmology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 10 (User ID: 20) - General Medicine
            [
                'stop_booking' => 0,
                'user_id' => 20,
                'department' => 19,
                'description' => 'Expert in general medicine with focus on diagnosis and treatment of common illnesses.',
                'specialization' => 'General Practitioner',
                'ex_year' => 7,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 0,
                'opd_fee' => 250,
                'video_fee' => 1000,
                'emg_fee' => 0,
                'zoom_client_id' => 'zoom_client_142',
                'zoom_secret_id' => 'zoom_secret_475',
                'insta_link' => 'https://instagram.com/dr.general',
                'fb_linik' => 'https://facebook.com/dr.general',
                'twitter_link' => 'https://twitter.com/dr_general',
                'you_tube_link' => 'https://youtube.com/dr.general',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 11 (User ID: 21) - Dentistry
            [
                'stop_booking' => 0,
                'user_id' => 21,
                'department' => 10,
                'description' => 'Dentist with expertise in orthodontics and root canal treatment.',
                'specialization' => 'Dentist',
                'ex_year' => 9,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 0,
                'opd_fee' => 300,
                'video_fee' => 1200,
                'emg_fee' => 0,
                'zoom_client_id' => 'zoom_client_132',
                'zoom_secret_id' => 'zoom_secret_465',
                'insta_link' => 'https://instagram.com/dr.dentistry',
                'fb_linik' => 'https://facebook.com/dr.dentistry',
                'twitter_link' => 'https://twitter.com/dr_dentistry',
                'you_tube_link' => 'https://youtube.com/dr.dentistry',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 12 (User ID: 22) - ENT
            [
                'stop_booking' => 0,
                'user_id' => 22,
                'department' => 6,
                'description' => 'Ear, nose, and throat specialist with expertise in sinus and hearing issues.',
                'specialization' => 'ENT Specialist',
                'ex_year' => 12,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 350,
                'video_fee' => 1200,
                'emg_fee' => 500,
                'zoom_client_id' => 'zoom_client_133',
                'zoom_secret_id' => 'zoom_secret_466',
                'insta_link' => 'https://instagram.com/dr.ent',
                'fb_linik' => 'https://facebook.com/dr.ent',
                'twitter_link' => 'https://twitter.com/dr_ent',
                'you_tube_link' => 'https://youtube.com/dr.ent',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 13 (User ID: 23) - Urology
            [
                'stop_booking' => 0,
                'user_id' => 23,
                'department' => 11,
                'description' => 'Urinary and male reproductive system specialist.',
                'specialization' => 'Urologist',
                'ex_year' => 11,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 400,
                'video_fee' => 1200,
                'emg_fee' => 600,
                'zoom_client_id' => 'zoom_client_134',
                'zoom_secret_id' => 'zoom_secret_467',
                'insta_link' => 'https://instagram.com/dr.urology',
                'fb_linik' => 'https://facebook.com/dr.urology',
                'twitter_link' => 'https://twitter.com/dr_urology',
                'you_tube_link' => 'https://youtube.com/dr.urology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 14 (User ID: 24) - Gastroenterology
            [
                'stop_booking' => 0,
                'user_id' => 24,
                'department' => 12,
                'description' => 'Digestive system specialist treating liver, IBS, ulcers, and colon health.',
                'specialization' => 'Gastroenterologist',
                'ex_year' => 13,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 0,
                'opd_fee' => 450,
                'video_fee' => 1200,
                'emg_fee' => 0,
                'zoom_client_id' => 'zoom_client_135',
                'zoom_secret_id' => 'zoom_secret_468',
                'insta_link' => 'https://instagram.com/dr.gastro',
                'fb_linik' => 'https://facebook.com/dr.gastro',
                'twitter_link' => 'https://twitter.com/dr_gastro',
                'you_tube_link' => 'https://youtube.com/dr.gastro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 15 (User ID: 25) - Nephrology
            [
                'stop_booking' => 0,
                'user_id' => 25,
                'department' => 13,
                'description' => 'Kidney specialist, dialysis and chronic kidney disease management.',
                'specialization' => 'Nephrologist',
                'ex_year' => 12,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 500,
                'video_fee' => 1200,
                'emg_fee' => 700,
                'zoom_client_id' => 'zoom_client_136',
                'zoom_secret_id' => 'zoom_secret_469',
                'insta_link' => 'https://instagram.com/dr.nephro',
                'fb_linik' => 'https://facebook.com/dr.nephro',
                'twitter_link' => 'https://twitter.com/dr_nephro',
                'you_tube_link' => 'https://youtube.com/dr.nephro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 16 (User ID: 26) - Endocrinology
            [
                'stop_booking' => 0,
                'user_id' => 26,
                'department' => 14,
                'description' => 'Hormone and endocrine disorders specialist for diabetes and thyroid.',
                'specialization' => 'Endocrinologist',
                'ex_year' => 14,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 0,
                'opd_fee' => 450,
                'video_fee' => 1300,
                'emg_fee' => 0,
                'zoom_client_id' => 'zoom_client_137',
                'zoom_secret_id' => 'zoom_secret_470',
                'insta_link' => 'https://instagram.com/dr.endocrine',
                'fb_linik' => 'https://facebook.com/dr.endocrine',
                'twitter_link' => 'https://twitter.com/dr_endocrine',
                'you_tube_link' => 'https://youtube.com/dr.endocrine',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 17 (User ID: 27) - Pulmonology
            [
                'stop_booking' => 0,
                'user_id' => 27,
                'department' => 15,
                'description' => 'Lung and respiratory care specialist treating asthma, COPD, and pneumonia.',
                'specialization' => 'Pulmonologist',
                'ex_year' => 11,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 400,
                'video_fee' => 1200,
                'emg_fee' => 600,
                'zoom_client_id' => 'zoom_client_138',
                'zoom_secret_id' => 'zoom_secret_471',
                'insta_link' => 'https://instagram.com/dr.pulmonology',
                'fb_linik' => 'https://facebook.com/dr.pulmonology',
                'twitter_link' => 'https://twitter.com/dr_pulmonology',
                'you_tube_link' => 'https://youtube.com/dr.pulmonology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 18 (User ID: 28) - Oncology
            [
                'stop_booking' => 0,
                'user_id' => 28,
                'department' => 16,
                'description' => 'Cancer specialist providing chemotherapy, radiotherapy, and supportive care.',
                'specialization' => 'Oncologist',
                'ex_year' => 15,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 0,
                'opd_fee' => 600,
                'video_fee' => 1400,
                'emg_fee' => 0,
                'zoom_client_id' => 'zoom_client_139',
                'zoom_secret_id' => 'zoom_secret_472',
                'insta_link' => 'https://instagram.com/dr.oncology',
                'fb_linik' => 'https://facebook.com/dr.oncology',
                'twitter_link' => 'https://twitter.com/dr_oncology',
                'you_tube_link' => 'https://youtube.com/dr.oncology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 19 (User ID: 29) - Rheumatology
            [
                'stop_booking' => 0,
                'user_id' => 29,
                'department' => 17,
                'description' => 'Autoimmune and musculoskeletal specialist for arthritis and lupus.',
                'specialization' => 'Rheumatologist',
                'ex_year' => 12,
                'active' => 1,
                'video_appointment' => 1,
                'clinic_appointment' => 1,
                'emergency_appointment' => 0,
                'opd_fee' => 450,
                'video_fee' => 1200,
                'emg_fee' => 0,
                'zoom_client_id' => 'zoom_client_140',
                'zoom_secret_id' => 'zoom_secret_473',
                'insta_link' => 'https://instagram.com/dr.rheumatology',
                'fb_linik' => 'https://facebook.com/dr.rheumatology',
                'twitter_link' => 'https://twitter.com/dr_rheumatology',
                'you_tube_link' => 'https://youtube.com/dr.rheumatology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Doctor 20 (User ID: 30) - Anesthesiology
            [
                'stop_booking' => 0,
                'user_id' => 30,
                'department' => 18,
                'description' => 'Provides anesthesia and perioperative care for surgical patients.',
                'specialization' => 'Anesthesiologist',
                'ex_year' => 14,
                'active' => 1,
                'video_appointment' => 0,
                'clinic_appointment' => 1,
                'emergency_appointment' => 1,
                'opd_fee' => 500,
                'video_fee' => 0,
                'emg_fee' => 700,
                'zoom_client_id' => 'zoom_client_141',
                'zoom_secret_id' => 'zoom_secret_474',
                'insta_link' => 'https://instagram.com/dr.anesthesia',
                'fb_linik' => 'https://facebook.com/dr.anesthesia',
                'twitter_link' => 'https://twitter.com/dr_anesthesia',
                'you_tube_link' => 'https://youtube.com/dr.anesthesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('doctors')->insert($doctors);
        $this->command->info('20 Doctors created for users 11-30!');
    }
}